import { CATEGORY_NAMES } from "../constants";

export const categories = {
  all: "Alle",
  default: CATEGORY_NAMES.MISCELLANEOUS,
  others: [
    CATEGORY_NAMES.BLOCKED_PASSAGE,
    CATEGORY_NAMES.BOTTLENECK,
    CATEGORY_NAMES.CATAGLYSM,
    CATEGORY_NAMES.CHANNEL_FLOODING,
    CATEGORY_NAMES.OVERLOADED_DITCH,
  ],
};

export const reporter = {
  steps: [
    {
      label: "Position wählen",
      descriptionMarker: "Durch Verschieben der Karte können Sie die Position Ihrer Meldung bestimmen.",
      alertText: "Zu weit vom Landkreis entfernt",
    },
    {
      label: "Ereignis beschreiben",
      category: "Kategorie",
      categories: {
        default: categories.default,
        others: categories.others,
      },
      counties: {
        default: "Außerhalb",
        others: [
          "Bad Salzschlirf",
          "Burghaun",
          "Dipperz",
          "Ebersburg",
          "Ehrenburg",
          "Eichenzell",
          "Eiterfeld",
          "Flieden",
          "Fulda",
          "Gersfeld",
          "Großenlüder",
          "Hilders",
          "Hofbieber",
          "Hosenfeld",
          "Hünfeld",
          "Kalbach",
          "Künzell",
          "Neuhof",
          "Nüsttal",
          "Petersberg",
          "Poppenhausen",
          "Rasdorf",
          "Tann",
        ],
      },
      county: "Gemeinde",
      description: "Beschreibung (max. 400 Zeichen)",
      descriptionPlaceholder: "Beschreibung des Ereignisses (z. B. nähere Orts- und Zeitangaben)",
      descriptionMaxChars: 400,
      date: "Ereignistag",
      time: "Uhrzeit (ca.)",
      pictureUpload: "Bild(er) hochladen (max. 3 - 10 MB, optional):",
      pictureChange: "Bild(er) bearbeiten (max. 3 - 10 MB, optional):",
      pictureRemove: "Bild löschen",
      pictureLocked: "Meldungsbilder können nicht editiert werden",
      feedback:
        "Für eine Rückmeldung zur Freigabe können Sie ihre E-Mail-Adresse eingeben (sie wird nicht öffentlich angezeigt).",
      feedbackEdit: "E-Mail-Adresse des Meldungsurhebers / der Meldungsurheberin",
      mail: "E-Mail (freiwillig)",
    },
    {
      label: "Meldung absenden",
      accept: "Durch einen Klick auf 'Senden' akzeptieren Sie die Datenschutzbestimmungen.",
      acceptEdit: "Durch einen Klick auf 'Bearbeiten' wird die Meldung unwiederruflich bearbeitet.",
    },
  ],
  finalStep: {
    thanks: "Vielen Dank für Ihre Teilnahme!",
    inputValidation: "Ihre Eingabe wird nun geprüft und ist bis zur Freigabe als grauer Marker sichtbar:",
    emailFeedback: "Wenn Sie eine E-Mail Adresse angegeben haben, werden Sie nach der Freigabe informiert.",
    questions: "Sollten Sie Rückfragen haben, so können Sie sich gerne an uns wenden unter:",
    mail: "Starkregen@Landkreis-Fulda.de",
  },
  continue: "Weiter",
  back: "Zurück",
  cancel: "Abbrechen",
  send: "Senden",
  edit: "Bearbeiten",
  close: "Schliessen",
  default: {
    idIfEdit: null,
    activeStep: -1,
    categoryValue: categories.default,
    comment: "",
    adminComment: "",
    descriptionValue: "",
    dateValue: new Date(),
    mailValue: "",
    userMarkerPosition: undefined,
    captchaSolved: false,
    images: [],
    countyValue: "Fulda",
  },
};
